# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(501, 323)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setContentsMargins(20, 20, 20, 20)
        self.formLayout.setHorizontalSpacing(10)
        self.formLayout.setVerticalSpacing(15)
        self.formLayout.setObjectName("formLayout")
        self.grade = QtWidgets.QLabel(Dialog)
        self.grade.setObjectName("grade")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.grade)
        self.gradeLineEdit = QtWidgets.QLineEdit(Dialog)
        self.gradeLineEdit.setObjectName("gradeLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.gradeLineEdit)
        self.roast = QtWidgets.QLabel(Dialog)
        self.roast.setObjectName("roast")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.roast)
        self.roastLineEdit = QtWidgets.QLineEdit(Dialog)
        self.roastLineEdit.setObjectName("roastLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.roastLineEdit)
        self.ground = QtWidgets.QLabel(Dialog)
        self.ground.setObjectName("ground")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.ground)
        self.groundLineEdit = QtWidgets.QLineEdit(Dialog)
        self.groundLineEdit.setObjectName("groundLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.groundLineEdit)
        self.description = QtWidgets.QLabel(Dialog)
        self.description.setObjectName("description")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.description)
        self.descriptionLineEdit = QtWidgets.QLineEdit(Dialog)
        self.descriptionLineEdit.setObjectName("descriptionLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.descriptionLineEdit)
        self.price = QtWidgets.QLabel(Dialog)
        self.price.setObjectName("price")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.price)
        self.priceLineEdit = QtWidgets.QLineEdit(Dialog)
        self.priceLineEdit.setObjectName("priceLineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.priceLineEdit)
        self.weight = QtWidgets.QLabel(Dialog)
        self.weight.setObjectName("weight")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.weight)
        self.weightLineEdit = QtWidgets.QLineEdit(Dialog)
        self.weightLineEdit.setObjectName("weightLineEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.weightLineEdit)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.grade.setText(_translate("Dialog", "Сорт"))
        self.roast.setText(_translate("Dialog", "Обжарка"))
        self.ground.setText(_translate("Dialog", "Помол"))
        self.description.setText(_translate("Dialog", "Описание"))
        self.price.setText(_translate("Dialog", "Цена"))
        self.weight.setText(_translate("Dialog", "Вес"))
